### ISSUE TITLE
Include site header as a template file

### ISSUE THREAD

**Issue by danbleile** [washingtonstateuniversity/wsuwp-theme-lodge#11]
Let's include the site header as a separate file so it's easy overwrite in a child theme.
https://github.com/washingtonstateuniversity/wsuwp-theme-lodge/blob/4816d898ed3a5b2460153e0740a84491189c690d/header.php#L27

**Comment by nicdford** [comment]
Should probably use a template part to handle header/footer & any other global components we want to be overridable.

**Comment by nicdford** [comment]
I went ahead and Identified all the "big ones". We'll probably just want to keep an eye out for any other parts that we could templatize in the future.
